### ISSUE TITLE
Recorded talk

### ISSUE THREAD

**Issue by GEJ1** [pieandai-grenoble/2024-02-23-ml-models-web#2]
Hello,

Is it possible to access to the recorded talk? I'm really interested. 

Thank you!

Best,

Gustavo

**Comment by rclement** [comment]
Hi @GEJ1,
As stated on the original Pie&AI registration link with Eventbrite, this was an on-site only event without recording, sorry.
If there some more demand, we might try some recordings for the next events.

However, you can access the presented material and demos online freely:
- Slides: https://pieandai-grenoble.github.io/2024-02-23-ml-models-web/
- Samples:
    - https://pieandai-grenoble.github.io/2024-02-23-ml-models-web/samples/housing/index.html
    - https://pieandai-grenoble.github.io/2024-02-23-ml-models-web/samples/sentiment/index.html
    - https://pieandai-grenoble.github.io/2024-02-23-ml-models-web/samples/imaging/index.html
    - https://pieandai-grenoble.github.io/2024-02-23-ml-models-web/samples/imaging/live.html
